name: langgraph_client
description: A Dart client for the LangGraph API that enables Flutter and Dart applications to interact with LangGraph services, including threads, assistants, runs, and crons with support for streaming operations.
repository: https://github.com/EsotericTech/langgraph-client
version: 0.1.1

environment:
  sdk: ^3.6.0

dependencies:
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  sse_stream: ^1.0.2
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  mockito: ^5.4.4
